#pragma once

#define fpDB_BUILD_REVISION 1
#define BETON_BUILD_REVISION 1
#define VENGINE_BUILD_REVISION 1
#define SERVERDEFINE_BUILD_REVISION 1
#define XMLREADER_BUILD_REVISION 1

#define STLOGIN_BUILD_REVISION 1
#define LUA_BUILD_REVISION 1

#define CLIENT_BUILD_REVISION 1
#define F3D_BUILD_REVISION 1
#define WORLDBASE_BUILD_REVISION 1
#define WORLDDEFINE_BUILD_REVISION 1

#define STWORLD_BUILD_REVISION 1